language: cpp

os: linux
dist: trusty
sudo: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - ninja-build
            - g++-5
      env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.9
          packages:
            - ninja-build
            - g++-5 # somehow we need this one here.
            - clang-3.9
      env: MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - ninja-build
            - clang-5.0
      env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - make check_debug
  - make check_release
